services:
  agent:
    image: portainer/agent:latest
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - swarm-net
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:latest
    command: ["-H", "tcp://tasks.agent:9001", "--tlsskipverify"]
    ports:
      - "9000:9000"
    volumes:
      - /mnt/appdata/portainer:/data
    networks:
      - swarm-net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.myservice.rule=Host(`portainer.home.coruscant.casa`)"
        - "traefik.http.routers.myservice.entrypoints=https"
        - "traefik.http.routers.myservice.tls=true"
        - "traefik.http.services.myservice.loadbalancer.server.port=9000"

networks:
  swarm-net:
    external: true